version: '3.3'

networks:
  haproxy-compose:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:
  server-1:
    container_name: server-1
    image: nginx
    ports:
      - '80'
    volumes:
    - ./server-1:/usr/share/nginx/html
    networks:
      - haproxy-compose

  server-2:
    container_name: server-2
    image: nginx
    ports:
      - '80'
    volumes:
    - ./server-2:/usr/share/nginx/html
    networks:
      - haproxy-compose

  server-3:
    container_name: server-3
    image: nginx
    ports:
      - '80'
    volumes:
    - ./server-3:/usr/share/nginx/html
    networks:
      - haproxy-compose

  haproxy:
    container_name: haproxy-compose
    image: haproxy:2.6
    ports:
      - '80:80'
      - '443:443'
      - '1936:1936'
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - haproxy-compose